.github/workflows/ccpp.yml
.travis.yml

Add both travis build and github workflow to compare.

ci: add gtest run

---

include/opae/access.h
include/opae/buffer.h
include/opae/metrics.h
include/opae/mmio.h
include/opae/sysobject.h
include/opae/types.h

Fix spelling errors in public headers

---

cmake/modules/FindTbb.cmake

Required for fpgabist dma test.

build: add FindTbb.cmake to opae-libs

---

libopae-c/api-shell.c
tests/opae-c/test_umsg_c.cpp
tests/xfpga/test_umsg_c.cpp

Umsg: deprecate Umsg APIs

---

include/opae/cxx/core/pvalue.h

Fix issues identified by checkers.

---

include/opae/cxx/core/pvalue.h

opae-cxx: fix issue found by checker

---

include/opae/cxx/core/pvalue.h

opae-cxx: fix coding style

---

include/opae/vfio.h

vfio: add vfio.h to include/opae

---

include/opae/vfio.h

opaevfio: add opae_vfio_secure_open() API.

---

pyopae/CMakeLists.txt

fix pybind11 version

---

include/opae/log.h
plugins/xfpga/metrics/bmc/bmc.c
pyopae/CMakeLists.txt

fix fedora34 build errors

---

include/opae/mem_alloc.h

mem_alloc: add mem_alloc.h

---

plugins/xfpga/metrics/metrics_max10.h
plugins/xfpga/sysfs.c

fix metrics sysfs attributes path

---

libopae-c/pluginmgr.c
plugins/xfpga/sysfs.c

add oofa r1 device id 0xaf00 to plug-in

opae-libs: add iofsr1 device id

---

.github/workflows/ccpp.yml
.travis.yml
plugins/CMakeLists.txt
plugins/vfio/dfl.c
plugins/vfio/opae_vfio.h

* Fix codingstyle in dfl.c
* Add vfio subdirectory to plugins/CMakeLists.txt

vfio-plugin: codingstyle fix, add to cmake

---

CMakeLists.txt

- update opae tests and sim 2.0.0-2 tag in cmakelistt file

opae-libs: update opae tests and sim tag

---

cmake/modules/OPAEExternal.cmake

* refactor variable declaration/use
(like `src_dir` and `bin_dir`)
* test if preserve repos option is empty and set it to OFF if so
* add src_dir and download_dir to additional clean files if preserve repos is OFF

cmake: refactor/enhance OPAEExternal.cmake

---

cmake/modules/OPAEPackaging.cmake

Prepare to unify installation of python modules/utils by creating a macro
to be used by such.
The macro takes care of installation path, so that `make
DESTDIR=/path/to/root` and `cmake .. -DCMAKE_INSTALL_PREFIX` are
respected. It also supports RPM packaging which can use the generated list
of installed files.
Signed-off-by: Martin Hundebøll <mhu@silicom.dk>

cmake: packaging: add opae_python_install helper function

---

cmake/modules/OPAEPackaging.cmake

Add RPM_PACKAGE argument to opae_python_install function
* When this value is non-empty and cpack generator is RPM
* Check for CPACK_PACKAGE_DIRECTORY and default to CMAKE_BINARY_DIR
if not set
* set APPEND_CODE variable to logic to include in the install script
* Read record file into variable RECORD_FILE
* Append the contents of this file to the package files list
By adding this, this function can use this argument to tell cmake/cpack
to append a file list used in the legacy rpmbuild process.

cmake: support cpack/RPM in python_install

---

libopaeuio/opaeuio.c

libopaeuio: fix issues identified by checkers

---

plugins/xfpga/sysfs.c

opae-libs fix coding style

---

CMakeLists.txt

default BUILD_LIBOFS to ON

---

plugins/xfpga/metrics/metrics_max10.c
plugins/xfpga/sysfs.c

- Metics  Buffer Overflow in Bound String Copy
- SYSobject api Buffer Overflow in Bound String Copy

fix static code analysis issues buffer overflow

---

pyopaeuio/CMakeLists.txt
pyopaeuio/setup.py

Changes:
- update Cmakelist.txt to build and install setup.py
- add setup.py to install pyopaeuio module

opae-libs: add pyopaeuio pybind11 packaging

---

plugins/vfio/opae_vfio.c

fix coding style

---

pyopaeuio/pyopaeuio.cpp

opae-libs: fix uio region offset

---

tests/opae-c/CMakeLists.txt
tests/opae-c/test_metrics_c.cpp
tests/opae-c/test_object_c.cpp

opae-c: beef up api-shell.c test coverage

---

plugins/xfpga/sysfs.c

opae-libs: fix code style

---

libopaecxx/src/token.cpp

opaecxx: fix coding style

---

plugins/xfpga/enum.c
plugins/xfpga/error.c
plugins/xfpga/error_int.h

Fix coding style.

---

plugins/vfio/opae_vfio.c
plugins/vfio/plugin.c

libopae-v: begin implementation of events API

---

include/opae/vfio.h
libopaevfio/opaevfio.c
libopaevfio/opaevfiotest.c

libopaevfio: add interrupt support

---

cmake/modules/OFS.cmake
scripts/ofs/ofs-registers-schema.json
scripts/ofs/ofs_parse.py
scripts/ofs/umd-schema.json

ofs-parse: fix urls of schema refs

---

include/opae/dfl.h
libdfl/opae_dfl.c
tests/libdfl/CMakeLists.txt
tests/libudev-mock/udev-mock.h

libdfl: fix _udev_ctx locking

---

include/opae/vfio.h
libopaevfio/opaevfio.c
plugins/vfio/opae_vfio.c

libopaevfio, libopae-v: final touch-up for IRQs

---

plugins/vfio/opae_vfio.c

libopae-v: fix bugs in Register/UnregisterEvent()

---

libopaevfio/opaevfio.c

libopaevfio: correct coding style

---

plugins/vfio/opae_vfio.c

vfio-plugin: fix coding style

---

plugins/xfpga/enum.c
plugins/xfpga/properties.c
plugins/xfpga/sysfs.c

xfpga: implement workarounds for lack of afu_id

---

libopaevfio/opaevfio.c
plugins/vfio/opae_vfio.c

vfio-irq: changes for bringup of VFIO IRQs

---

libopaevfio/opaevfio.c

libopaevfio: don't "prime" the interrupt

---

tests/opae-c/test_object_c.cpp

New test cases have been added for SDL requirement - CT181.
Signed-off-by: Sivaramakrishnan, VenkataramananX <venkataramananx.sivaramakrishnan@intel.com>

New test cases have been added for SDL requirement - CT181

---

libopaevfio/opaevfio.c

libopaevfio: use linux/pci_regs.h for PCI constants

---

.github/workflows/ccpp.yml
cmake/modules/FindCap.cmake

Added Finder for libcap library
Libcap library used in host_exerciser_cmd.h. 
To get the capabilities for the host_exerciser binary.
Signed-off-by: ramyavv <ramyax.venkatesha@intel.com>

Cmake:FinaCap_module

---

.github/workflows/ccpp.yml
cmake/modules/FindUdev.cmake

Added Finder for libudev library
Libudev library used in fpgaperf_counter.
Signed-off-by: ramyavv <ramyax.venkatesha@intel.com>

Cmake: FindUdev_module

---

tests/opae-c/test_buffer_c.cpp
tests/opae-c/test_event_c.cpp
tests/opae-c/test_mmio_c.cpp
tests/opae-c/test_object_c.cpp
tests/opae-c/test_pluginmgr_c.cpp

Unit test cases have been updated for SDL-CT196 requirements.
Signed-off-by: Sivaramakrishnan, VenkataramananX <venkataramananx.sivaramakrishnan@intel.com>

Unit test cases have been updated for SDL-CT196 requirements.

---

tests/opae-c/CMakeLists.txt
tests/opae-c/test_sdl_c.cpp

Unit test cases updated for SDL CT196 requirements.
Signed-off-by: Sivaramakrishnan, VenkataramananX <venkataramananx.sivaramakrishnan@intel.com>

Unit test cases updated for SDL CT196 requirements.

---

libopae-c/pluginmgr.c

add bcce/bccf device ids to pluginmgr

---

include/opae/dfl.h
libdfl/opae_dfl.c
tests/libdfl/test_libdfl.cpp

libdfl: misc cleanup, error paths, coding style
