OPAE/opae-libs

- cmake/modules/OPAETest.cmake
Enable coverage generation for test binaries and test static
libraries.
> coverage: enable coverage generation

- cmake/modules/OPAECompiler.cmake
clang-9: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
clang-9: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
> fix clang issue -argument unused during compilation: '-pie'

- cmake/modules/OPAEPackaging.cmake
Check for the presence of the lsb_release binary. When found, use
it to determine the specific Debian distro, then calculate the name
of the json-c library package based on the distro info.
> packaging: add Debian json-c package detection.

- plugins/xfpga/buffer.c
- plugins/xfpga/common.c
- plugins/xfpga/common_int.h
- plugins/xfpga/mmap.c
- tests/opae-cxx/test_buffer_cxx_core.cpp
- tests/xfpga/test_buffer_c.cpp
Previously, the mmap flags used by the huge page allocation code
were replicated in several of the source files and even in some of
the test code. Move the flags to common_int.h and use that as the
single definition of the flags.
Allocation requests for 2MB hugepages were being satisfied from
the kernel's default huge page pool. Change the 2MB allocation flags
to explicitly request these of the 2MB pool.
> xfpga: use single source of truth for mmap flags

- cmake/modules/FindUUID.cmake
- cmake/modules/Findjson-c.cmake
The warning are
CMake Warning:
Value of JSON-C_PKG_CONFIG_INCLUDE_DIRS contained a newline; truncating
CMake Warning:
Value of UUID_PKG_CONFIG_INCLUDE_DIRS contained a newline; truncating
This happens because using pkg-config has a newline in its output.
To remove the newline, use the OUTPUT_STRIP_TRAILING_WHITESPACE option of
execute_process.
> Fix cmake warnings when finding uuid and json-c include paths

- CMakeLists.txt
- cmake/modules/OPAEExternal.cmake
- external/CMakeLists.txt
Add option to skip refreshing the repos controlled by
opae_external_project_add. This preserves any local changes to
the repos that live within an external/ directory.
> cmake: add OPAE_PRESERVE_REPOS option

- tests/xfpga/test_metadata_c.cpp
- tests/xfpga/test_reconf_c.cpp
The bitstream metadata tests and the reconf tests create mock
metadata strings. The bitstream GUID in those metadata strings
had embedded the non-printable 0xb7 character. Replace the embedded
character with its hex escape equivalent \xb7.
> tests: fix clang++ error with non-printable char

- CMakeLists.txt
- external/CMakeLists.txt
Allows specifying the git tag to load for the corresponding external
repository.
> cmake: add OPAE_TEST_TAG and OPAE_SIM_TAG

- plugins/xfpga/sysfs.c
The device portion of the regex was assuming that the numbers would
be decimal only. Add the hex digits to the pattern.
> xfpga: fix device field of PCIE_PATH_PATTERN

- include/opae/types_enum.h
- plugins/xfpga/reconf.c
When provided as a part of the flags parameter to fpgaReconfigureSlot(),
this flag causes the AFU user clocks programming step to be skipped.
> xfpga: add FPGA_RECONF_SKIP_USRCLK flag

- plugins/xfpga/sysfs.c
readlink returns the number of bytes written.
If that fills the buffer, then the NULL assignment will overflow.
Reduce the buffer size parameter in readlink by 1 to
ensure there is space for the NULL.
> Fix possible buffer overflow

- plugins/xfpga/metrics/metrics_max10.c
-Buffer Overflow - Array Index Out of Bounds
> opae-libs: Static code analysis -  Buffer overflow

- plugins/xfpga/event.c
- plugins/xfpga/types_int.h
- tests/xfpga/test_events_c.cpp
The events API was always using index 0 when registering for interrupts.
Use the number of interrupts available along with a bitset of interrupts
already set for validating registering events. Also, save the interrupt
index in the event_handle data structure for associating interrupt
number with the event. This is used when unregistering for events.
> xfpga: fix irq use in events API

- pyopae/opae.cpp
- tests/pyopae/test_properties.py
- tests/pyopae/test_shared_buffers.py
- tests/pyopae/test_sysobject.py
* change the find method binding to default to use FPGA_OBJECT_GLOB
* change test_sysobject to find sysfs objects for n3000 platform
> pyopae: change 'find' to use glob, fix tests

- plugins/xfpga/token_list.c
A parent token will never exist in a virtualized environment,
because there is no fme sysfs entry. Report this as a debug
finding instead of flagging a false error.
> token_list: convert OPAE_ERR to OPAE_DBG

- include/opae/cxx/core/pvalue.h
- plugins/xfpga/metrics/afu_metrics.c
- plugins/xfpga/metrics/metrics_utils.c
Using clang static analyzer scan-build turns up a few issues.
Fixing the not returning failures is the more serious.
> A static analysis check

- plugins/xfpga/open.c
The openclose open_06 test simulated malloc failures show
that malloc failures in wsid_tracker_init need to be handled.
So check the returns and cleanup on failures.
> Improve malloc error handling in xfpga_fpgaOpen

- CMakeLists.txt
This reverts commit ada8bd1170bd1dec58fc92ea07e686b49d8758fd, reversing
changes made to 38c747d836b9246497784e9bd700c184a161ea94.
Change needs to go into `release/2.0.0`
Signed-off-by: Asgard Marroquin <asgard.marroquin@intel.com>
> Revert "Merge pull request #85 from OPAE/aravuri/fix_subrepo"

- CMakeLists.txt
Updates submodule targets to use branch `release/2.0.0`.
Also uses `SET` instead of `OPTION`, as `OPTION` seems to only work with boolean arguments.
Signed-off-by: Asgard Marroquin asgard.marroquin@intel.com
> Amarroqu/release 2.0.0 update submodule branchtargets

- CMakeLists.txt
Enables definition of external branch via CLI when configuring via `cmake`.
> Add CACHE, DOCSTRING to submodule branch targets 

- CMakeLists.txt
The option macro only allows a boolean ON/OFF value.
Use the appropriate set command instead.
> cmake: use set for OPAE_TEST_TAG and OPAE_SIM_TAG

- CMakeLists.txt
Lock in submodule targets for the release branch so that `opae-libs` OPAE dependencies do
not continue to target master HEAD.
This change is intentionally not being merged back into master, as the
opae-libs master branch should not naturally lock onto a release branch
"snapshot".
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> release: update submodule targets for 2.0.1-1

- cmake/modules/OPAEPackaging.cmake
Binary artifact generation for certain binaries generated during configuration
were not being generated on some platforms (e.g. a factory RHEL8.2 machine, which
by default does not define `python`). This is because the packaging script calls
for `python` directly, rather than the `PYTHON_EXECUTABLE` found by CMake during
configuration.
Commit changes the harded coded `python` call to `PYTHON_EXECUTABLE` to ensure
that packaging for these binary artifacts is identical to the rest of configuration.
Pulled from `opae-sdk` branch `release/1.3.7` (which had the old pre-submodule
configuration) here: https://github.com/OPAE/opae-sdk/commit/babc1c9d67d5b509ec9635c9fe279d5651b4751f
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> Specify same PYTHON_EXECUTABLE in packager as in CMake

- pyopae/CMakeLists.txt
Primary motivation for this is to take advantage #ifdef in pybind11 to
only call a now deprecated function, PyEval_InitThreads if the version of
Python is less than 3.9.
> pyopae: update pybind11 version to 2.6

- pyopae/CMakeLists.txt
pybind11 latest tag no longer builds on default el7 machines, at it has bumped
up the minimum supported cmake version.
https://github.com/pybind/pybind11/releases/tag/v2.6.0
This means that el7 won't compile a pybind11 version which supports python 3.9
(this is rationale for bumping pybind11 version in the first place). However, that
is likely out of scope of el7 - that support is on upstream Fedora systems for
example.
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> pybind11: add el7 guard in selecting pybind11 tag

- pyopae/CMakeLists.txt
Rather than relying on distribution, using cmake and python versions for
determining which version of pybind11 to fetch.
> build: use python & cmake version for pybind11

- .github/workflows/ccpp.yml
- cmake/modules/OPAEExternal.cmake
- external/CMakeLists.txt
- pyopae/CMakeLists.txt
- tests/pyopae/CMakeLists.txt
* Change opae_external_project_add macro
* Add DEFER option to opae_external_project_add macro
* Without DEFER, behavior is unchanged from before where external
projects are fetched at configure time
* With DEFER, behavior changes to adding a fetch target that fetches
the external project at build time
* Add a custom command to execute the steps it was doing before in
execute_process.
* Add a fetch target that depends on the output of the custom command
* Add opae_target_depends_external macro to add a dependency between a
target and a the fetch target.
* These changes make it so external projects are downloaded at build
time rather than configure time. This also optimizes configure/build
so external projects are only downloaded when making all targets or
making a target that depends on …
> build: change OPAEExternal macros

- external/CMakeLists.txt
Remove DEFER from pybind11 external project so that it gets pulled down
during the configuration step. opae-sdk needs this because it is using
CMake macros defined in pybind11's CMakeLists.
> build: revert pybind11 to not defer fetching

- include/opae/uio.h
- include/opae/vfio.h
Correct python command lines in opae/vfio.h.
> opaeuio: add opae/uio.h

- include/opae/vfio.h
> libopaevfio: remove obsolete struct member

- include/opae/cxx/core/errors.h
- include/opae/cxx/core/events.h
- include/opae/cxx/core/except.h
- include/opae/cxx/core/handle.h
- include/opae/cxx/core/properties.h
- include/opae/cxx/core/pvalue.h
- include/opae/cxx/core/shared_buffer.h
- include/opae/cxx/core/sysobject.h
- include/opae/cxx/core/token.h
- include/opae/cxx/core/version.h
- libopaecxx/samples/hello_fpga-1.cpp
- libopaecxx/src/events.cpp
- libopaecxx/src/except.cpp
- libopaecxx/src/shared_buffer.cpp
- libopaecxx/src/token.cpp
Run clang-format to auto-fix coding style violations.
The changes are all about reordering #includes to meet Google style
coding format.
> fix codingstyle for cpp files

- libopae-c/CMakeLists.txt
Signed-off-by: Martin Hundebøll <mhu@silicom.dk>
> libopae-c: build libopae-c-ase only when ase is enabled

- CMakeLists.txt
- libopaevfio/CMakeLists.txt
- plugins/CMakeLists.txt
* Add two compile options for enabling/disabling building of:
* libopaevfio
* libopaeuio
* libopae-v (in plugins/vfio)
* Move vfio compile check to top CMakeLists and only check if
libopaevfio is enabled.
* Add a little more information about vfio check failure.
> cmake: add options/guards for building vfio/uio

- CMakeLists.txt
When opae-libs is added as a subdirectory (like in opae-sdk) then
CMAKE_SOURCE_DIR is the root of the parent repository. Changing it to
CMAKE_CURRENT_SOURCE_DIR makes it relative to this CMakeLists.txt.
> cmake: fix path to vfiocheck.c

- CMakeLists.txt
- cmake/modules/OPAEExternal.cmake
- cmake/modules/OPAETest.cmake
- external/CMakeLists.txt
- tests/CMakeLists.txt
* set cmake minimum version to 3.10
* change `LIST` cmake type to `INTERNAL` to resolve warnings about
implicit conversion to `STRING`
* set `ENABLE_EXPORTS` to ON for test executables.
The test system uses `dladdr` for aid in injecting errors for negative tests
but the use of `dladdr` will not work with newer versions of cmake unless
explicitly setting `ENABLE_EXPORTS` to `ON`.
> cmake: set min. version to 3.10, fix warnings

- libopae-c/CMakeLists.txt
> opae-libs, cmake: BUILD_ASE -> OPAE_BUILD_SIM

- libopaeuio/opaeuio.c
The location of the uio/ directory within sysfs was changed.
Update opae_uio_init to support both paths.
> libopaeuio: update sysfs glob for dfl drivers

- libopae-c/adapter.h
- libopae-c/api-shell.c
- plugins/vfio/plugin.c
- plugins/xfpga/plugin.c
- tests/opae-c/dummy_plugin.c
- tests/xfpga/test_plugin_c.cpp
Removes unused entry points supports_device() and supports_host()
from the adapter table.
> plugin: remove unused adapter entry points

- include/opae/log.h
- tests/opae-c/test_enum_c.cpp
- tests/opae-c/test_mmio_c.cpp
- tests/opae-c/test_umsg_c.cpp
- tests/opae-cxx/test_handle_cxx_core.cpp
- tests/xfpga/test_afu_metrics_c.cpp
- tests/xfpga/test_buffer_c.cpp
- tests/xfpga/test_enum_c.cpp
- tests/xfpga/test_events_c.cpp
- tests/xfpga/test_metrics_c.cpp
- tests/xfpga/test_mmio_c.cpp
- tests/xfpga/test_mock_errinj_c.cpp
- tests/xfpga/test_open_close_c.cpp
- tests/xfpga/test_umsg_c.cpp
Use OPAE_MSG, OPAE_ERR, and OPAE_DBG instead.
> logging: deprecate FPGA_MSG, FPGA_ERR, FPGA_DBG

- cmake/modules/OPAETest.cmake
* Upgrade gtest to version 1.10.
Upgrading allows tests to be written with latest functionality
included better test parameterization.
* Switch to using opae_external_project_add instead of manually
setting up gtest include/library related variables.
IOW, because the gtest directory is added as a subdirectory,
now a test simply links to gtest_main target to get include/link
paths.
> gtest: upgrade to gtest 1.10 / use opae macro

- cmake/modules/OFS.cmake
Use OPAE_LIBS_ROOT when referencing dependancy ofs_parse.py
> ofs-umd: fix ofs_add_driver cmake macro

- scripts/ofs_parse.py
While libyaml is often available, it is hardly universal. The
performance improvement for header file generation here is not so
important that the script should break altogether.
To allow both implementations to work, riff on the import guidelines at
https://pyyaml.org/wiki/PyYAMLDocumentation#installation
Signed-off-by: Chip Bilbrey <chip.bilbrey@intel.com>
> ofs_parse: fix requirement on libyaml

- scripts/ofs_parse.py
This workaround is needed as a quick fix for broken EL7. The stub almost
certainly has misbehaviours, but is sufficient to produce correct output
for the single .yml input used from the repo.
Tested against python3-3.6.8-18.el7.x86_64 in C7, as well as a locally-
built installation of Python 3.7.7.
Signed-off-by: Chip Bilbrey <chip.bilbrey@intel.com>
> ofs_parse: add get_source_segment() stub for Python <3.8

- plugins/xfpga/sysfs.c
- tests/xfpga/test_sysfs_c.cpp
fpgaTokenGetObject() Recursively walks in SYSFS directory hierarchy
if SYS object API finds pattern “**” in path, recursive glob code walks in sub folders for SYSFS attribute.
Example:  Sysfs path :dfl*/*spi*/spi_master/spi*/**/security/*flash_count
fpgaTokenGetObject(token, “dfl*/*spi*/spi_master/spi*/**/security/*flash_count"
, &fpga_object, FPGA_OBJECT_GLOB);
Object API function make_sysfs_object() search’s in sub sysfs directory’s recursively
dfl*/*spi*/spi_master/spi*/*/security/*flash_count
dfl*/*spi*/spi_master/spi*/*/*/security/*flash_count
dfl*/*spi*/spi_master/spi*/*/*/*/security/*flash_count
> opae-libs: Add recursive glob support to SYSOBJECT API

- CMakeLists.txt
- pyopaeuio/CMakeLists.txt
- pyopaeuio/pyopaeuio.cpp
- pyopaeuio/pyopaeuio.h
-add pybind11 support to opaeuio module
Python functions
Open() : opens opae uio  device
Close()
Read32() reads 32 bit register
Read64() reads 64 bit register
write32() writes 32 bit register
write 64() writes 64 bit register
> opae-libs: add python bindings for opaeuio module

- scripts/ofs_parse.py
- scripts/umd.py
- tests/ofs_driver/ofs_test.yml
Simplify schema of input yaml file by:
* Assuming one driver implementation at top level
(instead of having a list of drivers).
* Allow 'api' keyword with Python text as the value.
* This text gets parsed using ast.parse and the same function
information (function name, args, return type...) is extracted to
later be fed into 'write_header
* Add 'api_functions' function to do processing mentioned above
* Refactor routine to extract the body of a nested block
(functions, if, while, etc.) into a function called 'get_body_text'
* Change schema in test yaml file
> ofs_parse: simplify schema

- cmake/modules/OFS.cmake
- scripts/umd.py
Python 3.9 ast NodeVisitor has a visit_Constant interface whereas older
versions used visit_Num and visit_Str.
This change:
* refactors/updates c_visitor class to implement
* visit_Constant
* visit_Str
* visit_Num
* visit_Index
* visit_Name
* changes visit_Subscript to visit node.slice
* adds umd.py to dependencies in 'ofs_add_driver' cmake macro
With the new visitor methods in c_visitor, the index value in a '[]'
operator will resolve to the correct value in Python 3.9 as well as
older versions.
> ofs: fix umd.py code gen script

- cmake/modules/OPAETest.cmake
Change opae_test_add function to check for this variable.
If set, it will treat is an indication to run the gtests
with xml output.
> cmake: add OPAE_GTEST_OUTPUT cmake variable

- plugins/xfpga/error.c
blacklist is problematic language.
In this case it refers to the not reporting errors that match the
entries in the error_exclude[].  So refer to the specific list
instead of the general term.
> opae-libs: reword blacklist to error exclude list

- tests/xfpga/test_metrics_max10_c.cpp
-Test pass on latest fedora and ubuntu os
-Test fails in CI,disable test case to unblock ci
> opae-libs: disable max10 test case

- plugins/vfio/opae_vfio.c
Current implementation of get_guid copies the input bytes (uint64_t *h)
in reverse order but because it does so per byte, the result is 32-bit
MMIO accesses. This change dereferences the two 64-bit words and calls
bswap_64 to have the bytes swapped and assigns the result to the output
guid variable.
> vfio-plugin: fix get_guid to use 64bit rd

- plugins/vfio/opae_vfio.c
For compatibility with previous implementations of the method.
> Don't fail in vfio_fpgaMapMMIO() when mmio_ptr is NULL

- libopae-c/pluginmgr.c
Add another line to the the plugin manager vendor/device id that
associates opae-v with 8086:af00. Doing this will cause the plugin
manager to load both plugins (xfpga and opae-v) whenever it detects a
platform of 8086:af00.
> opae-c: associate af00 with opae-v

- plugins/vfio/opae_vfio.c
Implement a vfio_reset routine that simply notifies user that it isn't
implemented but returns FPGA_OK.
> vfio-plugin: stub out vfio_reset

- libopaevfio/opaevfio.c
- plugins/vfio/opae_vfio.c
* Remove call to opae_vfio_buffer_free in free_buffer_list as this is
taken care of by libopaevfio.
* Move call to destroy buffers before destroying vfio related structures
that have file descriptors that will be closed.
> vfio: fix order of freeing buffers

- cmake/modules/OPAECompiler.cmake
'make lcov' runs commands to zero counters, run tests, then catpure end
counters and remove coverage from an exclude list before generating html
coverage report.
> build: add 'lcov' target in cmake

- cmake/modules/OPAECompiler.cmake
Change lcov custom target to only be added when it doesn't already exist
and build type is Coverage.
> build: check for lcov target

- libopaevfio/opaevfio.c
* Add function, setup_pci_command, that turns on bus mastering and mem
enable if either one is not set.
* Call setup_pci_command from opae_vfio_device_init
* Update return code and include pciaddr in error message in next
error-checked call after calling setup_pci_command.
> libvfio: set bus master, mmio when opening

- libopae-c/pluginmgr.c
- plugins/vfio/opae_vfio.c
- plugins/xfpga/metrics/metrics_max10.c
- plugins/xfpga/metrics/metrics_max10.h
- plugins/xfpga/sysfs.c
- plugins/xfpga/sysfs_int.h
- tests/xfpga/test_metrics_max10_c.cpp
- tests/xfpga/test_sysfs_c.cpp
Add support for the officially reservered PCI device id
for OFS devices.
Signed-off-by: Matthew Gerlach <matthew.gerlach@linux.intel.com>
> add support for PCI device id bcce

- .github/workflows/ccpp.yml
* Use a matrix strategy on the build job
* Run lcov zero/capture if build type is Coverage
* Run test if build type is Coverage or Debug
* Run covaeralls step if build type is Coverage
> ci: fixup workflow file to include coverage

- include/opae/cxx/core/handle.h
- include/opae/cxx/core/token.h
- libopaecxx/src/handle.cpp
- libopaecxx/src/token.cpp
- tests/opae-cxx/test_handle_cxx_core.cpp
Add get_parent() accessor to the token class. Enables
querying a token::ptr_t based on token::token_'s parent.
Add get_token() accessor to the handle class. Enables
querying a token::ptr_t base on handle::token_.
> cxx bindings: add token and parent accessors

- libopaecxx/src/token.cpp
> libopaecxx: fix coding style error

- include/opae/vfio.h
- libopaevfio/opaevfio.c
- plugins/vfio/opae_vfio.c
- plugins/vfio/opae_vfio.h
The implementation is currently limited to support for
FPGA_EVENT_ERROR.
> opae-v: implement the events API

- libopaevfio/opaevfio.c
Add an ERR statement when the ioctl to enable, unmask, mask, or
disable IRQs fails.
> libopaevfio: add logging when ioctl fails

- plugins/vfio/opae_vfio.c
Check if the first two 64-bit values are zero and ignore this BAR if
either is zero. This is a workaround until we get DFL encoded in DVSEC;
> vfio-plugin: ignore BARs without valid DFL

- plugins/xfpga/metrics/metrics_max10.c
- plugins/xfpga/metrics/metrics_max10.h
- plugins/xfpga/metrics/metrics_utils.c
- tests/xfpga/test_metrics_max10_c.cpp
N6010 sensor sysfs  path: /sys/class/fpga_region/region0/dfl-fme.0/dfl_dev.2/n6010bmc-hwmon.2.auto/hwmon/
IOFS R1 sensor path :  "/sys/bus/pci/devices/%s/fpga_region/region*/dfl-fme.*/"
"dfl_dev.*/subdev_spi_altera.*.auto/spi_master/spi*/spi*.*/"
"*-hwmon.*.auto/hwmon/hwmon*/*_label"
Max10 metrics recursive function with input  "*dfl_*/**/hwmon/hwmon*/" enumerates both N6010 and IOFSR1 sensor paths
> opae-libs: fix metrics sysfs path for n6010

- libopaevfio/opaevfio.c
Adds a check for invalid IRQ vector argument (subindex) to the
IRQ APIs. The given vector must be less than the irq->count.
> libopaevfio: add safeguards for invalid vectors

- tests/xfpga/test_mock_errinj_c.cpp
fpgaAssignPortToInterface() related unit test cases removed.
Signed-off-by: Sivaramakrishnan, VenkataramananX <venkataramananx.sivaramakrishnan@intel.com>
> fpgaAssignPortToInterface() related unit test cases removed.

- plugins/xfpga/sysfs.c
Assuming all sysfs files have size 4096 is wrong, as the kernel supports
specifying a static size for binary attributes. Take this into account
by using the size reported by stat(1) instead of the configured page
size.
Signed-off-by: Martin Hundebøll <mhu@silicom.dk>
> plugins: xfpga: support sysfs object sizes above 4096 bytes
